baseURL: 'https://shahar.blog/'
languageCode: 'en-us'
defaultContentLanguage: 'en'
defaultContentLanguageInSubdir: true  # This forces /en/ in URLs
title: 'Shahar Glazner - Dev Blog'
theme: 'hugo-theme-stack'

# Multilingual configuration
languages:
  en:
    contentDir: 'content/en'  # CRITICAL: Must specify contentDir
    languageName: English
    languageCode: en-us
    languageDirection: ltr
    title: Shahar Glazner - Dev Blog
    weight: 1
    params:
      description: "Personal development blog covering software engineering, web development, and tech insights"
      author:
        name: Shahar Glazner
        email: shahar@example.com
        link: https://github.com/shahargl
      github: shahargl
      twitter: shaharglazner
      linkedin: shaharglazner
      comments:
        enabled: true
        provider: giscus
        giscus:
          repo: shahargl/blog
          repoID: R_kgDOPDwrew
          category: Announcements
          categoryID: DIC_kwDOPDwre84CsM_C
          mapping: pathname
          strict: 0
          reactionsEnabled: 1
          emitMetadata: 0
          inputPosition: bottom
          theme: preferred_color_scheme
          lang: en
          loading: lazy
    menu:
      main:
        - identifier: posts
          name: Posts
          url: /en/posts/    # Match the permalink from hugo list all
          weight: 10
        - identifier: tags
          name: Tags
          url: /en/tags/
          weight: 20
        - identifier: categories
          name: Categories
          url: /en/categories/
          weight: 30
        - identifier: about
          name: About
          url: /en/about/    # Match the permalink from hugo list all
          weight: 40

  he:
    contentDir: 'content/he'  # CRITICAL: Must specify contentDir
    languageName: עברית
    languageCode: he-il
    languageDirection: rtl
    title: שאר גלזנר - בלוג פיתוח
    weight: 2
    params:
      description: "בלוג פיתוח אישי המכסה הנדסת תוכנה, פיתוח web ותובנות טכנולוגיות"
      author:
        name: שאר גלזנר
        email: shahar@example.com
        link: https://github.com/shahargl
      github: shahargl
      twitter: shaharglazner
      linkedin: shaharglazner
      comments:
        enabled: true
        provider: giscus
        giscus:
          repo: shahargl/blog
          repoID: R_kgDOPDwrew
          category: Announcements
          categoryID: DIC_kwDOPDwre84CsM_C
          mapping: pathname
          strict: 0
          reactionsEnabled: 1
          emitMetadata: 0
          inputPosition: bottom
          theme: preferred_color_scheme
          lang: he
          loading: lazy
    menu:
      main:
        - identifier: posts
          name: פוסטים
          url: /he/posts/    # Match the permalink from hugo list all
          weight: 10
        - identifier: tags
          name: תגיות
          url: /he/tags/
          weight: 20
        - identifier: categories
          name: קטגוריות
          url: /he/categories/
          weight: 30
        - identifier: about
          name: אודות
          url: /he/about/    # Match the permalink from hugo list all
          weight: 40

# Markup configuration
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    style: github

# Outputs
outputs:
  home: [HTML, RSS, JSON]

# Output formats
outputFormats:
  RSS:
    mediatype: application/rss+xml
    baseName: feed
    isPlainText: true
    notAlternative: true