baseURL = 'https://shahar.blog/'
languageCode = 'en-us'
title = 'Shahar Glazner - Dev Blog'
theme = 'hugo-theme-stack'

[params]
  # Basic info
  description = "Personal development blog covering software engineering, web development, and tech insights"
  
  # Author configuration
  [params.author]
    name = "Shahar Glazner"
    email = "shahar@example.com"
    link = "https://github.com/shahargl"
  
  # Social links
  github = "shahargl"
  twitter = "shaharglazner"
  linkedin = "shaharglazner"
  
  # Comments
  [params.comments]
    enabled = true
    provider = "giscus"
    
    [params.comments.giscus]
      repo = "shahargl/blog"
      repoId = "R_kgDOKj1234" # You'll need to replace this with your actual repo ID
      category = "Announcements"
      categoryId = "DIC_kwDOKj1234" # You'll need to replace this with your actual category ID
      mapping = "pathname"
      strict = "0"
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "top"
      theme = "preferred_color_scheme"
      lang = "en"
      loading = "lazy"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "github"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "feed"
    isPlainText = true
    notAlternative = true 